### PR TITLE
Use AMD transformation when importing, remove shim

### PR DESCRIPTION
**Pull request by fusion2004**
The changes in #23 to prepare for Fastboot 1.0 did not seem to work for me. The fastboot server would error when trying to `Fastboot.require('introJs')` in the shim.

This PR removes the need for the shim by using AMD transformation when importing.

### CODE REVIEW

**Comment by Exelord** [comment]
Nice :)
Is there any doc for the `transformation`?

**Comment by fusion2004** [comment]
Yes, I was following the ember-cli user guide: https://ember-cli.com/user-guide/#standard-anonymous-amd-asset

**Comment by Exelord** [comment]
Cool!
Looks great for me.
I will test it in this week and approve :)

@PoslinskiNet You should also check the `transformation` option. Isn't it what we were looking for? :D

**Comment by PoslinskiNet** [comment]
@fusion2004 nice 🥇.

Yes @Exelord we need to use this way instead if possible.

**Pull request merged**
